### ISSUE TITLE
루트 Vue 인스턴스 생성

### ISSUE THREAD

**Issue by JoisFe** [JoisFe/vue_product_project#1]
# Issue: 루트 Vue 인스턴스 생성

<br>

### Description
- Vue 애플리케이션 중심에 있는 루트 Vue 인스턴스 생성하고 간단하게 뷰에 무언가를 나타내서 첫 애플리케이션이 잘 작동하는지 알아보려함
- 생명주기 훅 추가를 하여 애플리케이션 인스턴스의 생명 주기 과정을 지켜보려함
<br>

### Todo
- [x] Vue 생성자를 이용해 애플리케이션을 시작하는 데 필요한 루트 Vue 인스턴스 생성
- [x] 애플리케이션 템플릿에 애플리케이션 인스턴스에서 나온 데이터를 표현해보기
- [x] 애플리케이션이 잘 작동하는지 확인 - (vue-devtools를 이용해보기)
- [x] 생명 주기 훅 추가
<br>

### Etc
- 기타사항
