### ISSUE TITLE
애플리케이션 이력 폼 추가 (사용자 주소, 결제 정보)

### ISSUE THREAD

**Issue by JoisFe** [JoisFe/vue_product_project#7]
# Issue: 애플리케이션 이력 폼 추가 (사용자 주소, 결제 정보)

<br>

### Description
- 사용자가 체크아웃하고 필요한 정보를 입력하기 위해 입력 폼을 추가하고자 함 -> 사용자가 주소와 결제 정보를 입력
- 애플리케이션 모델에 폼 데이터를 연결하기 위해 v-model 지시자를 이용하고자 함
- v-bind, v-for 지시자 등을 이용해 다양한 값 바인딩 (기본적인 입력, 셀렉트 박스, 체크 박스, 라디오 버튼) 을 해보려 함
<br>

### Todo
- [x] 체크아웃 폼 구현 
  - [x] 기본적인 입력 (이름, 성, 주소, 도시 입력)
  - [x] 셀렉트 박스 (주 입력)
  - [x] 체크 박스 (선물로 보내기 체크)
  - [x] 라디오 버튼 (자택, 직장 선택)
- [x] 입력값 다듬기
<br>

### Etc
- 기타사항
